### ISSUE TITLE
Build the skeleton of the main page

### ISSUE THREAD

**Issue by eyuelt** [tessa3/uxgraph#49]
Build the following components.

- navbar
- toolbar
- left sidenav
- canvas

It should roughly match the spec. Each component can be an empty placeholder. Just make sure when we go to the main page, we can clearly see the different components and they're in the right places.

**Comment by girum11** [comment]
Yup, build out basically the entire app with fake data. Everything should look like the spec, except that you should omit:

* the contents of the canvas (Eyuel will do this)
* real wiring to real Realtime API entities (I'll do this)

**Comment by girum11** [comment]
Nice! dev.uxgraph.io looks really good.

Now, within the main "Graph" area, can you add:

1. the secondary toolbar, complete with all of its icons
2. the FAB
3. the rest of the icons scattered around the page
4. change the left-side Drawer to be a fixed width, so that it does not shrink with the cards that will eventually go inside it.


Dope work!

**Comment by girum11** [comment]
Go ahead and close this one, I think you did basically all of the skeleton at this point.

**Comment by girum11** [comment]
Side-note, great work.
